version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    ports:
    - 4200:4200
  envoy-proxy:
    build:
      context: .
      dockerfile: ./docker/envoy.Dockerfile
    ports:
    - 8080:8080
  blog-service:
    build:
      context: .
      dockerfile: ./docker/blog.Dockerfile
    ports:
    - "9090:9090"
    environment:
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
  comment-service:
    build:
      context: .
      dockerfile: ./docker/comment.Dockerfile
    ports:
    - "9091:9091"
    environment:
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
  user-service:
    build:
      context: .
      dockerfile: ./docker/user.Dockerfile
    ports:
    - "9092:9092"
    environment:
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
    - JWT_SECRET=${JWT_SECRET}