version: '3'
services:
  blog-service:
    build:
      context: .
      dockerfile: ./blog.Dockerfile
    ports:
    - "9090:9090"
    environment:
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
  comment-service:
    build:
      context: .
      dockerfile: ./comment.Dockerfile
    ports:
    - "9091:9091"
    environment:
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}